"""add_fallback_fields

Revision ID: 1c5d46a54a51
Revises: f1a2b3c4d5e6
Create Date: 2026-03-16 17:59:36.864426
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '1c5d46a54a51'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('is_fallback', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('request_logs', sa.Column('fallback_from_slug', sa.String(length=255), nullable=True))
    op.add_column('services', sa.Column('fallback_service_id', sa.UUID(), nullable=True))
    op.add_column('services', sa.Column('fallback_on_statuses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'services', 'services', ['fallback_service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'fallback_on_statuses')
    op.drop_column('services', 'fallback_service_id')
    op.drop_column('request_logs', 'fallback_from_slug')
    op.drop_column('request_logs', 'is_fallback')
    # ### end Alembic commands ###
