"""add_load_test_tables

Revision ID: ecc101f47cba
Revises: 862ce616503d
Create Date: 2026-03-19 14:16:55.881254
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'ecc101f47cba'
down_revision: Union[str, None] = '862ce616503d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_test_tasks',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('test_path', sa.String(length=500), nullable=False),
    sa.Column('test_method', sa.String(length=10), nullable=False),
    sa.Column('test_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_load_test_tasks_owner_id', 'load_test_tasks', ['owner_id'], unique=False)
    op.create_index('ix_load_test_tasks_service_id', 'load_test_tasks', ['service_id'], unique=False)
    op.create_table('load_test_results',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('request_size', sa.Integer(), nullable=False),
    sa.Column('response_size', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['load_test_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_load_test_results_task_created', 'load_test_results', ['task_id', 'created_at'], unique=False)
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_load_test_results_task_created', table_name='load_test_results')
    op.drop_table('load_test_results')
    op.drop_index('ix_load_test_tasks_service_id', table_name='load_test_tasks')
    op.drop_index('ix_load_test_tasks_owner_id', table_name='load_test_tasks')
    op.drop_table('load_test_tasks')
    # ### end Alembic commands ###
